name: action workflow
on: action_workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world! execute action workflow first job first step!!!!!!!!!!!................"
