on: 
  - push
  - workflow_dispatch
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          echo "This is execute step-1 for line one."
          echo "This is execute step-1 for line two."
