name: First Workflow #This is name of workflow
on: workflow_dispatch #workflow execute 
jobs: 
  first-job: #first name of job
    runs-on: ubuntu-latest #based on which server it executes.
    steps: 
      - name: greeting of first step #name of the step.
        run: echo "Hello World!" #It execute in CMD.
      - name: code execution of first step
        run: echo "This is learning github actions."
  second-job: #first name of job
    runs-on: ubuntu-latest #based on which server it executes.
    steps:
      - name: second job first step
        run: echo "This is second job first step execution in CMD."
      - name: Print goodbye
        run: echo "Done - bye!"


